name: deploy-repoman
concurrency: repoman

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: australiaeast
      ENVIRONMENT: dev
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: ${{ env.REGION }}
        deploymentName: ${{ github.run_number }}
        template: deploy/main.bicep